version: '3'

tasks:
  desc: "start the project (for web-development only)"
  start:
    cmds:
      - npm run start:dev

  buildprod:
    desc: "build the production version of the project"
    cmds:
      - npm run build:prod
      - cp -Rf ./build/* ../databoutique-frontend-static
      - rm -Rf ./build

  # (Coming soon...)
  buildqa:
    desc: "build the quality assurance version of the project"
    cmds:
      - npm run build:qa
      - cp -Rf ./build/* ../databoutique-frontend-static
      - rm -Rf ./build
